filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
          add_error_key: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "careforall-logs-%{+yyyy.MM.dd}"

setup.template.name: "careforall-logs"
setup.template.pattern: "careforall-logs-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.ilm.enabled: false

logging.level: info
logging.to_files: false
