#!/bin/bash

echo "Stripe Webhook Local Testing Setup"
echo "==================================="
echo ""
echo "Your Stripe webhook listener is configured and running!"
echo ""
echo "Webhook Signing Secret (for local testing):"
echo "whsec_5f84d4bc58963cbf0206ea71fc0fddfd541988495cdbefb4496f15ed58b802d2"
echo ""
echo "The webhook listener is forwarding events to:"
echo "http://localhost:8080/api/payments/webhook/stripe"
echo ""
echo "Available test commands:"
echo "------------------------"
echo ""
echo "1. Test a successful payment:"
echo "   stripe trigger payment_intent.succeeded"
echo ""
echo "2. Test a failed payment:"
echo "   stripe trigger payment_intent.payment_failed"
echo ""
echo "3. Test a created payment:"
echo "   stripe trigger payment_intent.created"
echo ""
echo "4. View all available events:"
echo "   stripe trigger --help"
echo ""
echo "Note: The webhook endpoint is receiving 405 errors from the gateway."
echo "This appears to be an nginx configuration issue that may need adjustment."
echo ""
echo "Alternative: Test webhooks directly to the payment service (bypassing gateway):"
echo "Stop the current listener (Ctrl+C) and run:"
echo "stripe listen --forward-to localhost:3004/api/payments/webhook/stripe"